version: "3.8"

services:
  # Serviço n8n.io
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - WEBHOOK_URL=http://host.docker.internal:5678
      - N8N_REDIS_HOST=host.docker.internal
      - N8N_REDIS_PORT=6380
      - N8N_REDIS_PASSWORD=redis_n8n
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    networks:
      - n8n_network
    restart: always

  # Serviço Redis para n8n
  redis_n8n:
    image: redis:latest
    container_name: redis_n8n
    command:
      [
        "redis-server",
        "--requirepass",
        "redis_n8n",
        "--appendonly",
        "yes",
        "--port",
        "6379",
      ]
    ports:
      - "6380:6379"
    networks:
      - n8n_network
    restart: always

volumes:
  redis_data:
    external: false
    name: redis_data
  postgres_data:
    external: false
    name: postgres_data
  n8n_data:
    external: false
    name: n8n_data

networks:
  n8n_network:
    external: true
    name: n8n_network
